/// <reference types="@cloudflare/workers-types" />
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXTJS_ENV: string;
	SITE_PASSWORD: string;
	OPENROUTER_API_KEY: string;
	OPENROUTER_MODEL: string;
	OPENROUTER_SITE_URL: string;
	OPENROUTER_APP_NAME: string;
	FILES: R2Bucket;
	DB: D1Database;
	WORKER_SELF_REFERENCE: Fetcher;
	ASSETS: Fetcher;
}
