/// <reference types="@cloudflare/workers-types" />
// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	NEXTJS_ENV: string;
	SITE_PASSWORD: string;
	OPENROUTER_API_KEY: string;
	OPENROUTER_MODEL: string;
	OPENROUTER_SITE_URL: string;
	OPENROUTER_APP_NAME: string;
	PII_ENCRYPTION_KEY?: string;
	OPEN_PRICES_TOKEN?: string;
	FIREBASE_PROJECT_ID?: string;
	NEXT_PUBLIC_FIREBASE_API_KEY?: string;
	NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
	NEXT_PUBLIC_FIREBASE_PROJECT_ID?: string;
	NEXT_PUBLIC_FIREBASE_APP_ID?: string;
	NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID?: string;
	NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET?: string;
	FILES: R2Bucket;
	DB: D1Database;
	WORKER_SELF_REFERENCE: Fetcher;
	ASSETS: Fetcher;
}
