-- TENDED: Government Website Audit
--
-- DATA PRINCIPLE (CLAUDE.md): every dataset generated by volunteer work ships
-- with a free public download. Schema enforces this STRUCTURALLY:
--
--   * PRIVATE cluster: gov_audit_sessions
--       Holds PII / certification source of truth (user_id, submission_id).
--       Never exported.
--
--   * PUBLIC cluster: gov_audit_site_evaluations, gov_audit_page_evaluations,
--                     gov_audit_auto_checks
--       Holds the work product. References ONLY public_session_ref (opaque
--       per-session UUID). PII columns physically excluded — public export
--       is safe by construction, not by a filter step.
--
-- The single cross-boundary key is public_session_ref. Erasure: delete the
-- private row; public rows orphan under a ref that resolves to no user.
-- See PRD §7 and §9.

-- ============ PRIVATE CLUSTER ============

CREATE TABLE gov_audit_sessions (
  id                  TEXT PRIMARY KEY,
  user_id             TEXT NOT NULL REFERENCES users(id),
  submission_id       TEXT NOT NULL REFERENCES submissions(id),
  task_template_id    TEXT NOT NULL REFERENCES task_templates(id),

  -- Volunteer must be on desktop to certify accessibility findings. Recorded
  -- at start; "mobile" / "tablet" sessions still complete but never certify.
  device              TEXT NOT NULL CHECK (device IN ('desktop','mobile','tablet','unknown')),

  -- Opaque random UUID — the ONLY value that appears in both clusters. Never
  -- the production session key; per-session (not per-user) so an outside
  -- observer cannot aggregate one volunteer's contributions across sessions.
  public_session_ref  TEXT NOT NULL UNIQUE,

  -- Lifecycle: in_progress → submitted → finalized (or flagged)
  status              TEXT NOT NULL DEFAULT 'in_progress'
    CHECK (status IN ('in_progress','submitted','finalized','flagged')),

  started_at          INTEGER NOT NULL,
  submitted_at        INTEGER,
  finalized_at        INTEGER,

  -- Derived on finalize:
  --   certified_minutes = Σ min(time_on_anchor_sec, 600) gated on completed
  --                       page rubric for that anchor
  --   integrity_score   ∈ [0,1] — rubric completeness × auto-check corroboration
  certified_minutes   INTEGER,
  integrity_score     REAL,

  -- The target descriptor the task assigned (e.g. "SNAP application page on
  -- CDSS"). Stored for audit-trail; never user-edited after start.
  target_descriptor   TEXT NOT NULL
);
CREATE INDEX idx_gov_audit_sessions_user ON gov_audit_sessions(user_id, started_at);
CREATE INDEX idx_gov_audit_sessions_submission ON gov_audit_sessions(submission_id);
CREATE INDEX idx_gov_audit_sessions_status ON gov_audit_sessions(status);

-- ============ PUBLIC CLUSTER ============
-- The public CSV / JSON export is built ONLY from these three tables. They
-- contain NO foreign key to users or sessions. Joining within the cluster
-- happens via public_session_ref.

CREATE TABLE gov_audit_site_evaluations (
  id                  TEXT PRIMARY KEY,
  public_session_ref  TEXT NOT NULL,
  site_domain         TEXT NOT NULL,            -- registrable domain only, no path

  -- Site-level rubric (answered once per session). See PRD §5.1.
  official_domain     INTEGER,                  -- bool: .gov / .us / state equiv
  https               INTEGER,                  -- bool
  mobile_responsive   TEXT CHECK (mobile_responsive IN ('pass','partial','fail','cant_tell')),
  language_access     INTEGER,                  -- bool
  site_search         TEXT CHECK (site_search IN ('pass','partial','fail','cant_tell')),
  mobile_firsthand    INTEGER,                  -- bool, optional volunteer report

  created_at          INTEGER NOT NULL
);
CREATE INDEX idx_gov_audit_site_eval_ref ON gov_audit_site_evaluations(public_session_ref);
CREATE INDEX idx_gov_audit_site_eval_domain ON gov_audit_site_evaluations(site_domain);

CREATE TABLE gov_audit_page_evaluations (
  id                  TEXT PRIMARY KEY,
  public_session_ref  TEXT NOT NULL,
  url                 TEXT NOT NULL,            -- query strings stripped before insert
  url_domain          TEXT NOT NULL,            -- registrable domain
  page_title          TEXT,

  -- Per-anchor measured time (cap-applied downstream in certified_minutes).
  time_on_anchor_sec  INTEGER,
  anchor_set_at       INTEGER,

  -- Observable rubric: pass | partial | fail | cant_tell. See PRD §5.2.
  accessibility       TEXT CHECK (accessibility IN ('pass','partial','fail','cant_tell')),
  acc_alt_text        TEXT CHECK (acc_alt_text IN ('pass','partial','fail','cant_tell')),
  acc_keyboard_nav    TEXT CHECK (acc_keyboard_nav IN ('pass','partial','fail','cant_tell')),
  acc_contrast        TEXT CHECK (acc_contrast IN ('pass','partial','fail','cant_tell')),
  acc_zoom_200        TEXT CHECK (acc_zoom_200 IN ('pass','partial','fail','cant_tell')),
  task_completion     TEXT CHECK (task_completion IN ('pass','partial','fail','cant_tell')),
  maintained          TEXT CHECK (maintained IN ('pass','partial','fail','cant_tell')),

  -- Experiential rubric: integer 1-5.
  nav_1to5            INTEGER CHECK (nav_1to5 BETWEEN 1 AND 5),
  clarity_1to5        INTEGER CHECK (clarity_1to5 BETWEEN 1 AND 5),
  trust_1to5          INTEGER CHECK (trust_1to5 BETWEEN 1 AND 5),
  overall_1to5        INTEGER CHECK (overall_1to5 BETWEEN 1 AND 5),

  -- Free text — moderated before any public export pulls these columns.
  intent_text         TEXT,
  blocker_text        TEXT,
  fix_text            TEXT,
  text_moderation_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (text_moderation_status IN ('pending','approved','rejected')),

  -- Domain+path navigation trail; query strings stripped before persist.
  nav_trail_json      TEXT,

  created_at          INTEGER NOT NULL
);
CREATE INDEX idx_gov_audit_page_eval_ref ON gov_audit_page_evaluations(public_session_ref);
CREATE INDEX idx_gov_audit_page_eval_domain ON gov_audit_page_evaluations(url_domain);

CREATE TABLE gov_audit_auto_checks (
  id                  TEXT PRIMARY KEY,
  public_session_ref  TEXT NOT NULL,
  url                 TEXT NOT NULL,            -- query strings stripped

  https_ok            INTEGER,
  http_status         INTEGER,
  load_ok             INTEGER,
  axe_violations      INTEGER,                  -- total count
  axe_summary_json    TEXT,                     -- {ids, counts, impact}
  check_mode          TEXT NOT NULL             -- 'browser_rendering' | 'fetch_only' | 'skipped'
    CHECK (check_mode IN ('browser_rendering','fetch_only','skipped')),

  checked_at          INTEGER NOT NULL
);
CREATE INDEX idx_gov_audit_auto_checks_ref ON gov_audit_auto_checks(public_session_ref);
