-- TENDED: EMS rate research
--
-- DATA PRINCIPLE (CLAUDE.md): every dataset generated by volunteer work ships
-- with a free public download. Enforced STRUCTURALLY by splitting the schema:
--
--   * PRIVATE cluster: the existing `submissions` row stays the source of
--     truth for who-did-what. user_notes holds the draft form + the
--     public_session_ref UUID; user_id ties it to a person.
--
--   * PUBLIC cluster: ems_rate_reports holds the work product — the
--     researched ambulance rates. References ONLY public_session_ref. NO
--     user_id, NO submission_id. Public CSV/JSON export reads only this
--     table, so PII leakage is impossible by construction.
--
-- The single cross-boundary key is public_session_ref. Erasure: delete the
-- user + their submission; ems_rate_reports rows orphan under a ref that
-- resolves to no one. The published rate research stays available.

CREATE TABLE ems_rate_reports (
  id                  TEXT PRIMARY KEY,

  -- Opaque random UUID generated at COMMIT time and stored in submissions.user_notes.
  -- The only value that appears in both the private and public clusters.
  public_session_ref  TEXT NOT NULL UNIQUE,

  -- The provider/city the volunteer was assigned by round-robin. Recorded
  -- here (not just on the submission) so the export is fully self-describing.
  provider_name       TEXT NOT NULL,
  city                TEXT NOT NULL,
  state               TEXT NOT NULL,

  -- BLS base rate.
  bls_amount          TEXT,                                      -- nullable; stored as text to preserve "1200.00" form
  bls_source_url      TEXT,
  bls_not_found       INTEGER NOT NULL DEFAULT 0 CHECK (bls_not_found IN (0,1)),

  -- ALS base rate.
  als_amount          TEXT,
  als_source_url      TEXT,
  als_not_found       INTEGER NOT NULL DEFAULT 0 CHECK (als_not_found IN (0,1)),

  -- Per-mile rate.
  mileage_amount      TEXT,
  mileage_source_url  TEXT,
  mileage_not_found   INTEGER NOT NULL DEFAULT 0 CHECK (mileage_not_found IN (0,1)),

  -- Treat-no-transport fee.
  tnt_amount          TEXT,
  tnt_source_url      TEXT,
  tnt_not_found       INTEGER NOT NULL DEFAULT 0 CHECK (tnt_not_found IN (0,1)),
  tnt_description     TEXT,

  -- Context.
  effective_date      TEXT,                                      -- ISO yyyy-mm-dd from a <input type=date>
  zip_codes           TEXT,                                      -- free text — moderation status below gates publishing
  notes               TEXT,

  -- Lifecycle.
  --   submitted: volunteer hit submit; data captured but not yet org-approved.
  --   published: org reviewer approved the underlying submission; safe to export.
  created_at          INTEGER NOT NULL,
  published_at        INTEGER,

  -- Free-text moderation gate — mirrors the gov_audit pattern. Structured
  -- numeric/url columns publish on `published_at`; the free-text `notes`
  -- column publishes only when status = 'approved'.
  text_moderation_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (text_moderation_status IN ('pending','approved','rejected'))
);
CREATE INDEX idx_ems_rate_reports_ref ON ems_rate_reports(public_session_ref);
CREATE INDEX idx_ems_rate_reports_state_city ON ems_rate_reports(state, city);
CREATE INDEX idx_ems_rate_reports_published ON ems_rate_reports(published_at);
