-- TENDED: Food Access Price Audit — public/private cluster split
--
-- DATA PRINCIPLE (CLAUDE.md): every dataset generated by volunteer work ships
-- with a free public download. Until now the food-audit work product
-- (audit_item_captures, audit_photos, open_prices_contributions) referenced
-- audits.id, and audits.id co-locates with audits.user_id — meaning the public
-- export was safe only by query carefulness. This migration removes the back
-- channel STRUCTURALLY, mirroring the gov-audit and ems-rate patterns:
--
--   * PRIVATE cluster: audits (PII source-of-truth — user_id, submission_id,
--     credited_hours, validation flags), audit_validation_flags, stores,
--     volunteer_trust, audit_photo_exif (camera GPS / timestamp; used only by
--     the fraud pipeline, never exported).
--
--   * PUBLIC cluster: audit_public_summaries (one row per submitted audit,
--     store-level facts only), audit_item_captures (per-basket-item rows),
--     audit_photos (vision results + R2 keys, no EXIF), and
--     open_prices_contributions. All public tables reference ONLY
--     public_session_ref — NO FK to users, audits, or any private row.
--
-- The single cross-boundary key is audits.public_session_ref. Erasure: delete
-- the audits row + audit_validation_flags + audit_photo_exif; the public rows
-- orphan under a ref that resolves to no person. The work product stays.

-- Defer FK checks until end of transaction. We rebuild three FK-linked tables
-- in sequence and intermediate states transiently violate FKs.
PRAGMA defer_foreign_keys = ON;

-- ============ Step 1: add public_session_ref to private audits row ============

ALTER TABLE audits ADD COLUMN public_session_ref TEXT;

-- Backfill: every existing audit gets a fresh opaque ref. The format is just a
-- 32-char hex string — matches the opacity of crypto.randomUUID() in shape
-- without depending on it; the value is never parsed.
UPDATE audits
   SET public_session_ref = lower(hex(randomblob(16)))
 WHERE public_session_ref IS NULL;

CREATE UNIQUE INDEX idx_audits_public_session_ref ON audits(public_session_ref);

-- ============ Step 2: PUBLIC audit_public_summaries ============
-- One row per audit, containing only store-level facts that are safe to publish.
-- Built at migration time from existing audits; new audits insert into it at
-- submit time (lib/audit-pipeline.ts).

CREATE TABLE audit_public_summaries (
  public_session_ref       TEXT PRIMARY KEY,
  -- Store snapshot — frozen at submit time so the published row stays stable
  -- even if the shared stores row is later edited.
  store_name               TEXT,
  store_address            TEXT,
  store_geocode_lat        REAL,
  store_geocode_lng        REAL,
  -- Observable store-level facts.
  store_type_observed      TEXT,
  ebt_observation          TEXT,
  submitted_at             INTEGER,
  -- Set when validation_status flips to 'verified' (export pulls only verified rows).
  verified_at              INTEGER
);
CREATE INDEX idx_aps_verified ON audit_public_summaries(verified_at);

INSERT INTO audit_public_summaries
  (public_session_ref, store_name, store_address, store_geocode_lat, store_geocode_lng,
   store_type_observed, ebt_observation, submitted_at, verified_at)
SELECT a.public_session_ref,
       COALESCE(a.store_name_snapshot, s.name),
       COALESCE(a.store_address_snapshot, s.address),
       COALESCE(a.store_geocode_lat_snapshot, s.geocode_lat),
       COALESCE(a.store_geocode_lng_snapshot, s.geocode_lng),
       a.store_type_observed,
       a.ebt_observation,
       a.submitted_at,
       CASE WHEN a.validation_status = 'verified' THEN a.submitted_at ELSE NULL END
  FROM audits a
  LEFT JOIN stores s ON s.id = a.store_id;

-- ============ Step 3: split audit_photos EXIF into private side-table ============
-- Done BEFORE we rebuild audit_photos so the EXIF columns are still readable.

CREATE TABLE audit_photo_exif (
  photo_id           TEXT PRIMARY KEY,
  exif_timestamp     INTEGER,
  exif_geocode_lat   REAL,
  exif_geocode_lng   REAL
);

INSERT INTO audit_photo_exif (photo_id, exif_timestamp, exif_geocode_lat, exif_geocode_lng)
SELECT id, exif_timestamp, exif_geocode_lat, exif_geocode_lng
  FROM audit_photos
 WHERE exif_timestamp IS NOT NULL
    OR exif_geocode_lat IS NOT NULL
    OR exif_geocode_lng IS NOT NULL;

-- ============ Step 4: rebuild the three FK-linked public tables ============
-- Strategy: create all three _new tables, populate them, then drop the three
-- old tables, then rename in dependency order (captures last is fine because
-- the renamed _new tables already exist with the right names internally — we
-- just need the rename to land before commit-time FK validation).
--
-- We rebuild audit_item_captures, audit_photos, and open_prices_contributions
-- all at once because audit_photos and open_prices_contributions FK into
-- audit_item_captures, and audit_item_captures has FK from audit_photos in the
-- old shape. Doing them in lock-step with defer_foreign_keys=ON keeps the
-- final state consistent.

CREATE TABLE audit_item_captures_new (
  id                    TEXT PRIMARY KEY,
  public_session_ref    TEXT NOT NULL,
  basket_item_id        TEXT NOT NULL,
  stock_status          TEXT NOT NULL
    CHECK (stock_status IN ('in-stock','out-of-stock','not-sold-at-this-store')),
  price_usd             REAL,
  size_value            REAL,
  size_unit             TEXT,
  produce_pricing_mode  TEXT,
  photo_id              TEXT,
  captured_at           INTEGER NOT NULL,
  UNIQUE (public_session_ref, basket_item_id)
);

INSERT INTO audit_item_captures_new
  (id, public_session_ref, basket_item_id, stock_status, price_usd, size_value,
   size_unit, produce_pricing_mode, photo_id, captured_at)
SELECT c.id, a.public_session_ref, c.basket_item_id, c.stock_status, c.price_usd,
       c.size_value, c.size_unit, c.produce_pricing_mode, c.photo_id, c.captured_at
  FROM audit_item_captures c
  JOIN audits a ON a.id = c.audit_id;

-- audit_item_capture_id intentionally has no FK declaration: the migration
-- swap order would transiently dangle, and FK enforcement on this column adds
-- no integrity guarantee the public_session_ref doesn't already provide.
CREATE TABLE audit_photos_new (
  id                       TEXT PRIMARY KEY,
  public_session_ref       TEXT NOT NULL,
  audit_item_capture_id    TEXT,
  r2_key                   TEXT NOT NULL,
  thumb_r2_key             TEXT,
  sha256                   TEXT,
  uploaded_at              INTEGER NOT NULL,
  vision_validation_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (vision_validation_status IN ('pending','running','passed','failed','skipped')),
  vision_result_json       TEXT,
  ocr_price_value          REAL
);

INSERT INTO audit_photos_new
  (id, public_session_ref, audit_item_capture_id, r2_key, thumb_r2_key, sha256,
   uploaded_at, vision_validation_status, vision_result_json, ocr_price_value)
SELECT p.id, a.public_session_ref, p.audit_item_capture_id, p.r2_key, p.thumb_r2_key,
       p.sha256, p.uploaded_at, p.vision_validation_status, p.vision_result_json,
       p.ocr_price_value
  FROM audit_photos p
  JOIN audits a ON a.id = p.audit_id;

-- audit_item_capture_id intentionally has no FK declaration: see audit_photos_new.
CREATE TABLE open_prices_contributions_new (
  id                    TEXT PRIMARY KEY,
  public_session_ref    TEXT NOT NULL,
  audit_item_capture_id TEXT NOT NULL,
  basket_item_id        TEXT NOT NULL,
  product_code          TEXT,
  status                TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','sent','failed','skipped')),
  attempt_count         INTEGER NOT NULL DEFAULT 0,
  last_error            TEXT,
  open_prices_id        TEXT,
  posted_at             INTEGER,
  next_retry_at         INTEGER,
  created_at            INTEGER NOT NULL,
  UNIQUE (audit_item_capture_id)
);

INSERT INTO open_prices_contributions_new
  (id, public_session_ref, audit_item_capture_id, basket_item_id, product_code,
   status, attempt_count, last_error, open_prices_id, posted_at, next_retry_at, created_at)
SELECT o.id, a.public_session_ref, o.audit_item_capture_id, o.basket_item_id,
       o.product_code, o.status, o.attempt_count, o.last_error, o.open_prices_id,
       o.posted_at, o.next_retry_at, o.created_at
  FROM open_prices_contributions o
  JOIN audits a ON a.id = o.audit_id;

-- Drop the old tables (children first to keep transient FK violations contained).
DROP TABLE open_prices_contributions;
DROP TABLE audit_photos;
DROP TABLE audit_item_captures;

ALTER TABLE audit_item_captures_new RENAME TO audit_item_captures;
ALTER TABLE audit_photos_new RENAME TO audit_photos;
ALTER TABLE open_prices_contributions_new RENAME TO open_prices_contributions;

CREATE INDEX idx_aic_session_ref ON audit_item_captures(public_session_ref);
CREATE INDEX idx_aph_session_ref ON audit_photos(public_session_ref);
CREATE INDEX idx_aph_capture ON audit_photos(audit_item_capture_id);
CREATE INDEX idx_op_contrib_session_ref ON open_prices_contributions(public_session_ref);
CREATE INDEX idx_op_contrib_retry ON open_prices_contributions(status, next_retry_at);
