import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { getDb } from "@/lib/cf";
import { loadVerifiedAudits } from "@/lib/audit-aggregate";
import { getLocale } from "@/lib/i18n";

// Reads from D1 (Cloudflare context), unavailable at prerender. Edge cache on
// the export endpoints carries performance; the index itself is force-dynamic.
export const dynamic = "force-dynamic";

export const metadata = {
  title: "Public datasets — Tended",
  description:
    "Free, public-domain datasets produced by Tended volunteers. Every dataset ships with a free CSV and JSON download under CC0.",
};

const COPY = {
  en: {
    overline: "Free & public domain",
    title: "Public datasets",
    intro:
      "Every dataset generated by volunteer work on Tended ships with a free public download. No login, no fees — reuse freely under CC0.",
    rows: "rows",
    foodTitle: "Food access prices",
    foodBody:
      "Volunteer-collected shelf-tag prices for 6 neighborhood staples across food retailers nationwide.",
    govTitle: "Government website accessibility audits",
    govBody:
      "Volunteer evaluations of government web pages — accessibility, clarity, and task completion — corroborated by automated checks. Free-text comments appear only after moderation.",
    viewDashboard: "View dashboard",
    downloadCsv: "CSV",
    downloadJson: "JSON",
  },
  es: {
    overline: "Gratis y de dominio público",
    title: "Conjuntos de datos públicos",
    intro:
      "Cada conjunto de datos generado por el trabajo voluntario en Tended incluye una descarga pública gratuita. Sin inicio de sesión, sin costos — reutilízalo libremente bajo CC0.",
    rows: "filas",
    foodTitle: "Precios de acceso a alimentos",
    foodBody:
      "Precios de etiqueta de estante recopilados por voluntarios para 6 productos básicos del vecindario en tiendas de alimentos de todo el país.",
    govTitle: "Auditorías de accesibilidad de sitios web gubernamentales",
    govBody:
      "Evaluaciones de voluntarios de páginas web gubernamentales — accesibilidad, claridad y finalización de tareas — corroboradas por verificaciones automáticas. Los comentarios de texto libre aparecen solo después de la moderación.",
    viewDashboard: "Ver panel",
    downloadCsv: "CSV",
    downloadJson: "JSON",
  },
} as const;

export default async function DataIndexPage() {
  const locale = await getLocale();
  const c = COPY[locale];

  const report = await loadVerifiedAudits();
  const foodRows = report.verified_audits;

  const db = getDb();
  const govCountRow = await db
    .prepare(`SELECT COUNT(*) AS n FROM gov_audit_page_evaluations`)
    .first<{ n: number }>();
  const govRows = govCountRow?.n ?? 0;

  return (
    <>
      <a href="#main" className="skip-link">Skip to content</a>
      <SiteHeader />
      <main id="main" className="mx-auto max-w-5xl px-4 py-10">
        <header className="mb-8">
          <p className="text-xs uppercase tracking-wide text-body">{c.overline}</p>
          <h1 className="text-3xl font-semibold mt-1">{c.title}</h1>
          <p className="text-body mt-2 max-w-2xl">{c.intro}</p>
        </header>

        <ul className="grid gap-5 md:grid-cols-2">
          <li>
            <DatasetCard
              title={c.foodTitle}
              body={c.foodBody}
              count={`${foodRows.toLocaleString()} ${c.rows}`}
              dashboardHref="/data/food-access"
              dashboardLabel={c.viewDashboard}
              csvHref="/api/data/audits.csv"
              jsonHref={null}
              csvLabel={c.downloadCsv}
              jsonLabel={c.downloadJson}
            />
          </li>
          <li>
            <DatasetCard
              title={c.govTitle}
              body={c.govBody}
              count={`${govRows.toLocaleString()} ${c.rows}`}
              dashboardHref={null}
              dashboardLabel={c.viewDashboard}
              csvHref="/api/data/gov-audits.csv"
              jsonHref="/api/data/gov-audits.json"
              csvLabel={c.downloadCsv}
              jsonLabel={c.downloadJson}
            />
          </li>
        </ul>
      </main>
      <SiteFooter />
    </>
  );
}

function DatasetCard({
  title,
  body,
  count,
  dashboardHref,
  dashboardLabel,
  csvHref,
  jsonHref,
  csvLabel,
  jsonLabel,
}: {
  title: string;
  body: string;
  count: string;
  dashboardHref: string | null;
  dashboardLabel: string;
  csvHref: string;
  jsonHref: string | null;
  csvLabel: string;
  jsonLabel: string;
}) {
  return (
    <div className="flex h-full flex-col rounded-lg border border-line bg-white p-5">
      <p className="text-xs uppercase tracking-wide text-body">{count}</p>
      <h2 className="mt-1 text-lg font-semibold">{title}</h2>
      <p className="mt-2 text-sm text-body">{body}</p>
      <div className="mt-auto flex flex-wrap items-center gap-x-4 gap-y-2 pt-4 text-sm">
        {dashboardHref && (
          <Link
            href={dashboardHref}
            className="inline-flex items-center gap-1 font-medium text-forest hover:underline"
          >
            {dashboardLabel}
            <ArrowRight className="size-4" />
          </Link>
        )}
        <a className="text-forest underline-offset-2 hover:underline" href={csvHref}>
          {csvLabel}
        </a>
        {jsonHref && (
          <a className="text-forest underline-offset-2 hover:underline" href={jsonHref}>
            {jsonLabel}
          </a>
        )}
      </div>
    </div>
  );
}
